# Generated by Django 4.2.4 on 2023-09-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_admin_userbase_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
