# Generated by Django 4.2.4 on 2023-09-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
