# Generated by Django 4.2.4 on 2023-09-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
